name: Deploy Worker

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: prepare config
        run: sed -i "s/KV_NAME/$KV_NAME/g" wrangler.toml
      env:
        KV_NAME: ${{ secrets.KV_NAME }}

      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

